// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetNodeInfoRaw() {
  return window['go']['main']['App']['GetNodeInfoRaw']();
}

export function GetNodeStatus() {
  return window['go']['main']['App']['GetNodeStatus']();
}

export function GetPeers() {
  return window['go']['main']['App']['GetPeers']();
}

export function GetRPCBaseURL() {
  return window['go']['main']['App']['GetRPCBaseURL']();
}

export function GetUnconfirmedTxs(arg1) {
  return window['go']['main']['App']['GetUnconfirmedTxs'](arg1);
}

export function SetRPCBaseURL(arg1) {
  return window['go']['main']['App']['SetRPCBaseURL'](arg1);
}
