// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetNodeInfoRaw():Promise<string>;

export function GetNodeStatus():Promise<main.NodeStatus>;

export function GetPeers():Promise<Array<main.Peer>>;

export function GetUnconfirmedTxs(arg1:number):Promise<main.UnconfirmedTxs>;

export function SetRPCBaseURL(arg1:string):Promise<void>;
